[tool]
id          = "com.thelightphone.agenda"
label       = "Agenda"
versionCode = 8
versionName = "1.5.2"
orientation = "portrait"
permissions = ["android.permission.INTERNET", "android.permission.CAMERA", "android.permission.VIBRATE", "android.permission.SYSTEM_ALERT_WINDOW", "android.permission.POST_NOTIFICATIONS"]
# change if you run this on the emulator!
serverPackage = "com.lightos"
# serverPackage = "com.thelightphone.sdk.emulator"
