[tool]
id = "com.thelightphone.kaginews"
label = "Brief"
versionCode = 1
versionName = "1.0.0"
permissions = ["android.permission.INTERNET"]
serverPackage = "com.lightos"
# change if you run this on the emulator!
# serverPackage = "com.thelightphone.sdk.emulator"
